"""empty message

Revision ID: 056429854be1
Revises: f7379489e257
Create Date: 2024-06-03 02:04:45.960205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056429854be1'
down_revision = 'f7379489e257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
