"""empty message

Revision ID: 6ef6bfff5b73
Revises: fc829d59b7b1
Create Date: 2024-06-03 18:26:26.733093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef6bfff5b73'
down_revision = 'fc829d59b7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('user_timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('room_timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
