"""empty message

Revision ID: c3ab5259872b
Revises: 6ef6bfff5b73
Create Date: 2024-06-04 04:06:27.335641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ab5259872b'
down_revision = '6ef6bfff5b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime_utc', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('start_datetime_utc')

    # ### end Alembic commands ###
