"""empty message

Revision ID: fc829d59b7b1
Revises: 056429854be1
Create Date: 2024-06-03 17:49:47.179923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc829d59b7b1'
down_revision = '056429854be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('room_timezone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('room_timezone')
        batch_op.drop_column('user_timezone')

    # ### end Alembic commands ###
